[tool.poetry]
name = "nautobot-docker-compose"
version = "0.1.1"
description = ""
authors = ["John Doe <johndoe@mail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
nautobot = "2.4.4"

# nautobot-example-plugin = {path = "plugins/plugin_example", develop = true}
nautobot-golden-config = "^2.4.0"
nautobot-plugin-nornir = "^2.2.1"
nautobot-device-lifecycle-mgmt = "^2.2.1"
easysnmp = "^0.2.6"


[tool.poetry.dev-dependencies]
invoke = "*"
toml = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
